project:
  type: website
  output-dir: docs

website:
  title: "datamining_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: darkly.
    css: styles.css



